iptables -A INPUT -p tcp -m tcp --dport 17500 -j ACCEPT 
iptables -A INPUT -p tcp -m tcp --dport 11443 -j ACCEPT 
iptables -A INPUT -p tcp -m tcp --dport 1112 -j ACCEPT 
iptables -A INPUT -p tcp -m tcp --dport 3013 -j ACCEPT 
iptables -A INPUT -p tcp -m tcp --dport 18081 -j ACCEPT 
iptables -A INPUT -p tcp -m tcp --dport 8088 -j ACCEPT 
iptables -A INPUT -p tcp -m tcp --dport 8086 -j ACCEPT 
iptables -A INPUT -p tcp -m tcp --dport 8085 -j ACCEPT 
iptables -A INPUT -p tcp -m tcp --dport 8080 -j ACCEPT 
iptables -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT 
iptables -A INPUT -p tcp -m tcp --dport 17500 -j ACCEPT
iptables -A INPUT -p tcp -m tcp --dport 11443 -j ACCEPT
iptables -A INPUT -p tcp -m tcp --dport 1112 -j ACCEPT
iptables -A INPUT -p tcp -m tcp --dport 3013 -j ACCEPT
iptables -A INPUT -p tcp -m tcp --dport 18081 -j ACCEPT
iptables -A INPUT -p tcp -m tcp --dport 8080 -j ACCEPT
iptables -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -m tcp --dport 11443 -j ACCEPT 
iptables -A OUTPUT -p tcp -m tcp --dport 1112 -j ACCEPT 
iptables -A OUTPUT -p tcp -m tcp --dport 3013 -j ACCEPT 
iptables -A OUTPUT -p tcp -m tcp --dport 18081 -j ACCEPT 
iptables -A OUTPUT -p tcp -m tcp --dport 8088 -j ACCEPT 
iptables -A OUTPUT -p tcp -m tcp --dport 8086 -j ACCEPT 
iptables -A OUTPUT -p tcp -m tcp --dport 8085 -j ACCEPT 
iptables -A OUTPUT -p tcp -m tcp --dport 8080 -j ACCEPT 
iptables -A OUTPUT -p tcp -m tcp --dport 80 -j ACCEPT 
iptables -A OUTPUT -p tcp -m tcp --dport 17500 -j ACCEPT 
iptables -A OUTPUT -p udp -m udp --dport 20001 -j ACCEPT
iptables -A OUTPUT -p udp -m udp --dport 8011 -j ACCEPT
iptables -A OUTPUT -p udp -m udp --dport 11038 -j ACCEPT
iptables -A OUTPUT -p udp -m udp --dport 111 -j ACCEPT
iptables -A OUTPUT -p udp -m udp --dport 8011 -j ACCEPT
iptables -A OUTPUT -p udp -m udp --dport 81 -j ACCEPT
iptables -A OUTPUT -p tcp -m tcp --dport 11443 -j ACCEPT
iptables -A OUTPUT -p tcp -m tcp --dport 1112 -j ACCEPT
iptables -A OUTPUT -p tcp -m tcp --dport 3013 -j ACCEPT
iptables -A OUTPUT -p tcp -m tcp --dport 18081 -j ACCEPT
iptables -A OUTPUT -p tcp -m tcp --dport 8080 -j ACCEPT
iptables -A OUTPUT -p tcp -m tcp --dport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -m tcp --dport 17500 -j ACCEPT